### ISSUE TITLE
Unable to open the settings page 

### ISSUE THREAD

**Issue by BobSilent** [thkl/hm-influxdb#1]
After installation and reboot of CCU the settings page cannot be opened.

when trying to SSH into the CCU3 and trying to execute the command and exception is thrown
```
# node /usr/local/addons/hm-influxdb/index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hm-influxdb/index.js:2:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

also in the settings menu there seems to be a bug
![image](https://user-images.githubusercontent.com/13506173/123325528-6851ac80-d538-11eb-97c9-95b1e8a12be2.png)
the image is not shown

and as update a version 0.0.14 is shown, although only 0.0.1 exists.
when clicking Download link one is navigated to 
https://github.com/thkl/hap-homematic/releases/tag/0.0.14

seems that the released [hm-influxdb-0.0.1.tar.gz](https://github.com/thkl/hm-influxdb/releases/download/0.0.1/hm-influxdb-0.0.1.tar.gz) contains the items of  hap-homematic in `www` folder

**Comment by krid78** [comment]
I stumbled across the same behavior and tried a few approaches.

- I stopped the addon using `start-stop-daemon --stop --quiet  --oknodo  --retry 5  --pidfile /var/run/hm-influxdb.pid`. Then, I manually started it using `node /usr/local/addons/hm-influxdb/index.js`, seeing the following (full log: [port_in_use.log](https://github.com/thkl/hm-influxdb/files/9437614/port_in_use.log)).

```console
[2022-08-27 10:46:39.772] [Main] Config Path is /etc/config/addons/hm-influxdb
[2022-08-27 10:46:39.787] [InfluxLogger] Missing Database Settings ...
...
[2022-08-27 10:46:39.936] [Homematic Interface Manager] ****************************************************************************************************************************
[2022-08-27 10:46:39.938] [Homematic Interface Manager] *  Sorry the local port 9501 on your system is in use. Please make sure, self no other instance of this plugin is running.
[2022-08-27 10:46:39.938] [Homematic Interface Manager] *  you may change the initial port with the config setting for local_port in your config.json
[2022-08-27 10:46:39.939] [Homematic Interface Manager] *  giving up ... the homematic plugin is not able to listen for ccu events on %s until you fix this.
[2022-08-27 10:46:39.940] [Homematic Interface Manager] ****************************************************************************************************************************
...
[2022-08-27 10:46:49.309] [Homematic Interface Manager]  event unable to find Interface for [ 'cfl_VirtualDevices', 'INT0000004:0', 'CONFIG_PENDING', false ]
```

- Ok, so port 9501 is not available. As far as I can guess, CUxD is using this port already.

- So I modified the port in `lib/configserver.js`, as I do not have any idea how the config file could look like. Now it looks just fine (full log: [changed_port.log](https://github.com/thkl/hm-influxdb/files/9437615/changed_port.log)).

```console
node /usr/local/addons/hm-influxdb/index.js
[2022-08-27 10:57:24.686] [Main] Config Path is /etc/config/addons/hm-influxdb
...
[2022-08-27 10:57:24.784] [InfluxLoggerConfig] srv is running on port 19501
...
[2022-08-27 10:57:35.466] [Homematic Interface Manager] CCU Response for init at VirtualDevices with command http://192.168.178.10:9500,cfl_VirtualDevices ...Value ("") Error : (null)
```
Unfortunately, the web interface does still not appear. Thus, I can't set up the database.

@thkl , can you simply provide a sample configuration?

**Comment by krid78** [comment]
I also can't fugure out, why the update dialog shows (and links to) hap-homematic. There is no `hap` in the repository.
